# Generated by Django 5.0.1 on 2024-01-14 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registered_Startup', models.BooleanField(default=True)),
                ('StartupIndia_Program', models.BooleanField(default=False)),
                ('Program_Proof', models.ImageField(blank=True, upload_to='Registration Proof')),
                ('CompletedStartupIndia_Program', models.BooleanField(default=False)),
                ('Completion_Proof', models.ImageField(blank=True, upload_to='Completion Certificates')),
                ('Application_Status', models.BooleanField(default=False)),
                ('Application_StatusProof', models.ImageField(blank=True, upload_to='Application Statuses')),
                ('StartupTest_Email', models.BooleanField(default=False)),
                ('StartupTest_Appeared', models.BooleanField(default=False)),
                ('Presentation_Email', models.BooleanField(default=False)),
                ('Presentation_Appeared', models.BooleanField(default=False)),
                ('Fund_Confirmed', models.BooleanField(default=False)),
                ('CompanyRegistrationApplied', models.BooleanField(default=False)),
                ('SeedFund_Received', models.BooleanField(default=False)),
                ('Applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Startups_Progress_Report',
            },
        ),
    ]
